"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en-us" | "en-gb" | "ar-eg" | "fr" | "de";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const translationsData: Record<Language, Record<string, string>> = {
  "en-us": {
    // Login translations
    title: "At Church",
    subtitle: "Coptic Orthodox",
    slogan: '"Anchored in Faith, Connected in Love."',
    tab_login: "Sign In",
    tab_register: "New Account",
    email_label: "Email Address",
    password_label: "Password",
    forgot_password: "Forgot?",
    btn_signin: "Sign In",
    demo_login_prefix: "Demo login:",
    register_name_label: "Full Name",
    confirm_password_label: "Confirm Password",
    btn_create_account: "Create Account",
    help: "Help",
    privacy: "Privacy",
    terms: "Terms",
    placeholder_email: "name@example.com",
    placeholder_password: "••••••••",
    placeholder_name: "e.g. Fayez Shenouda",
    placeholder_min_chars: "Min 6 characters",
    placeholder_retype: "Re-type password",
    forgot_title: "Reset Password",
    forgot_instructions: "Enter your registered email address to reset your password.",
    forgot_instructions_step2: "A temporary verification code has been sent to your email.",
    mock_code_notice: "Mock Code: 123456",
    code_label: "Verification Code",
    new_password_label: "New Password",
    btn_reset_password: "Reset Password",
    btn_submit_new_password: "Update Password",
    back_to_login: "Back to Sign In",
    placeholder_code: "Enter 123456",
    error_email_not_found: "Email address not found.",
    error_invalid_code: "Invalid verification code. Use 123456.",
    error_passwords_dont_match: "Passwords do not match.",
    success_password_reset: "Password reset successful! Redirecting...",
    email_verified_msg: "Email verified! Enter the verification code.",
    error_password_too_short: "Password must be at least 6 characters.",
    step_1_title: "Step 1 of 3: Personal Info",
    step_2_title: "Step 2 of 3: Communication",
    step_3_title: "Step 3 of 3: Church Data & Account",
    reg_arabic_name_label: "Quadruple Name in Arabic",
    reg_english_name_label: "Full Name in English",
    reg_dob_label: "Date of Birth",
    reg_phone_label: "WhatsApp Number",
    btn_send_otp: "Send Verification Code",
    btn_send_email_link: "Send Verification Link",
    btn_sending_otp: "Sending...",
    btn_sent_otp: "Code Sent",
    email_link_sent_msg: "Verification link sent! Please check your email inbox and click the link to verify your email.",
    reg_otp_label: "Enter 6-digit Code",
    reg_otp_mock_notice: "Mock Mode: Enter any 6 digits.",
    reg_email_label: "Email Address (Optional)",
    reg_education_label: "School/College",
    reg_address_label: "Address for Visitation",
    btn_get_coordinates: "Get Current Location (Coordinates)",
    reg_coords_captured: "Coordinates captured.",
    reg_gov_label: "Church Selection",
    reg_gov_placeholder: "Select Governorate...",
    gov_assiut: "Assiut",
    gov_cairo: "Cairo",
    gov_alexandria: "Alexandria",
    reg_church_placeholder: "Select a governorate first.",
    reg_password_label: "Create Password",
    btn_back: "Back",
    btn_next: "Next",
    btn_another_church: "Another Church",
    placeholder_arabic_name: "Write your quadruple name in Arabic letters",
    placeholder_english_name: "Enter your quadruple name in English",
    placeholder_whatsapp: "+20 123 456 7890",
    placeholder_otp: "123456",
    placeholder_education: "Search institution...",
    placeholder_address: "Enter your detailed address...",
    error_arabic_name_regex: "Please enter exactly 4 names separated by spaces, using only Arabic letters.",
    error_english_name_regex: "Please enter exactly 4 names separated by spaces, using only English letters.",
    error_dob_required: "Date of birth is required.",
    error_whatsapp_required: "WhatsApp number is required.",
    error_otp_missing: "Please verify your phone number by sending and entering the OTP.",
    error_otp_invalid: "Please enter a valid 6-digit OTP.",
    error_email_invalid: "Please enter a valid email address.",
    error_education_required: "Please enter your educational institution.",
    error_address_required: "Please enter your full address.",
    error_coords_missing: "Please capture your coordinates for visitation.",
    error_gov_required: "Please select a governorate.",
    error_church_missing: "Please select at least 1 church.",
    error_church_max: "You can select a maximum of 5 churches.",
    error_password_short: "Password must be at least 6 characters.",
    reg_confirm_password_label: "Confirm Password",
    error_confirm_password_required: "Please confirm your password.",
    placeholder_confirm_password: "Re-type password",
    step_9_title: "Profile Photo",
    step_10_title: "Set Password",
    reg_photo_label: "Profile Photo",
    reg_photo_placeholder: "Add photo",
    btn_rotate: "Rotate",
    btn_remove_photo: "Remove",
    btn_upload_photo: "Upload Photo",
    btn_take_photo: "Take Photo",
    btn_capture: "Capture",
    btn_cancel: "Cancel",
    btn_skip: "Skip",

    // Dashboard translations
    dashboard_header: "Dashboard",
    welcome: "Welcome Back,",
    blessing: '"Peace be to this house and to all that dwell in it." Have a blessed day.',
    next_liturgy: "Next Liturgy Booking",
    confession: "Confession Session",
    reserved: "Reserved Services",
    class_group: "Spiritual Class Group",
    wisdom_title: "Spiritual Wisdom",
    wisdom_quote: '"Do not be afraid of the combat, and do not run away from it. If you fall, get up again, pray to the Lord, and push forward. The Savior is always near to help you."',
    wisdom_author: "— St. Anthony the Great",
    katameros_title: "Katameros (Daily Reading)",
    psalm_heading: "Psalm 23:1-3",
    psalm_text: '"The Lord is my shepherd; I shall not want. He makes me to lie down in green pastures; He leads me beside the still waters..."',
    john_heading: "John 15:5",
    john_text: '"I am the vine, you are the branches. He who abides in Me, and I in him, bears much fruit; for without Me you can do nothing."',
    read_full: "Read Full Katameros",
    book_liturgy: "Book Divine Liturgy",
    notice_board: "Church Notice Board",
    sunday_liturgy: "Sunday Liturgy - June 14",
    wednesday_liturgy: "Wednesday Liturgy - June 17",
    feast_liturgy: "Feast of Ascension Liturgy - June 18",
    main_hall: "Main Hall (Coptic/English)",
    chapel: "St. Mary Chapel (Arabic/Coptic)",
    sanctuary: "Main Sanctuary (Feast Liturgy)",
    capacity_120: "Capacity: 120/150 booked",
    capacity_15: "Capacity: 15/40 booked",
    capacity_45: "Capacity: 45/200 booked",
    book_space: "Book Space",
    retreat_badge: "Retreat Announcement",
    retreat_title: "Youth Spiritual Retreat 2026",
    retreat_text: "Registration for our Summer Youth Retreat is officially open. The retreat will take place from July 24-26. Speak with Father Antonios to register.",
    bible_badge: "Bible Study",
    bible_title: "Summer Book study on Isaiah",
    bible_text: "Every Thursday evening at 7:30 PM in the Fellowship Hall. Bring your own Bible. Live stream will also be available on our channel.",
    view_notices: "View all notices",
    nav_dashboard: "Dashboard",
    nav_bookings: "Bookings",
    nav_katameros: "Katameros",
    nav_community: "Community",
    nav_settings: "Settings",
    profile_logged_in: "Logged in as:",
    profile_settings: "Profile Settings",
    profile_logout: "Log Out"
  },
  "en-gb": {
    // Login translations
    title: "At Church",
    subtitle: "Coptic Orthodox",
    slogan: '"Anchored in Faith, Connected in Love."',
    tab_login: "Sign In",
    tab_register: "New Account",
    email_label: "Email Address",
    password_label: "Password",
    forgot_password: "Forgot?",
    btn_signin: "Sign In",
    demo_login_prefix: "Demo login:",
    register_name_label: "Full Name",
    confirm_password_label: "Confirm Password",
    btn_create_account: "Create Account",
    help: "Help",
    privacy: "Privacy",
    terms: "Terms",
    placeholder_email: "name@example.co.uk",
    placeholder_password: "••••••••",
    placeholder_name: "e.g. Fayez Shenouda",
    placeholder_min_chars: "Min 6 characters",
    placeholder_retype: "Re-type password",
    forgot_title: "Reset Password",
    forgot_instructions: "Enter your registered email address to reset your password.",
    forgot_instructions_step2: "A temporary verification code has been sent to your email.",
    mock_code_notice: "Mock Code: 123456",
    code_label: "Verification Code",
    new_password_label: "New Password",
    btn_reset_password: "Reset Password",
    btn_submit_new_password: "Update Password",
    back_to_login: "Back to Sign In",
    placeholder_code: "Enter 123456",
    error_email_not_found: "Email address not found.",
    error_invalid_code: "Invalid verification code. Use 123456.",
    error_passwords_dont_match: "Passwords do not match.",
    success_password_reset: "Password reset successful! Redirecting...",
    email_verified_msg: "Email verified! Enter the verification code.",
    error_password_too_short: "Password must be at least 6 characters.",
    step_1_title: "Step 1 of 3: Personal Info",
    step_2_title: "Step 2 of 3: Communication",
    step_3_title: "Step 3 of 3: Church Data & Account",
    reg_arabic_name_label: "Quadruple Name in Arabic",
    reg_english_name_label: "Full Name in English",
    reg_dob_label: "Date of Birth",
    reg_phone_label: "WhatsApp Number",
    btn_send_otp: "Send Verification Code",
    btn_send_email_link: "Send Verification Link",
    btn_sending_otp: "Sending...",
    btn_sent_otp: "Code Sent",
    email_link_sent_msg: "Verification link sent! Please check your email inbox and click the link to verify your email.",
    reg_otp_label: "Enter 6-digit Code",
    reg_otp_mock_notice: "Mock Mode: Enter any 6 digits.",
    reg_email_label: "Email Address (Optional)",
    reg_education_label: "School/College",
    reg_address_label: "Address for Visitation",
    btn_get_coordinates: "Get Current Location (Coordinates)",
    reg_coords_captured: "Coordinates captured.",
    reg_gov_label: "Church Selection",
    reg_gov_placeholder: "Select Governorate...",
    gov_assiut: "Assiut",
    gov_cairo: "Cairo",
    gov_alexandria: "Alexandria",
    reg_church_placeholder: "Select a governorate first.",
    reg_password_label: "Create Password",
    btn_back: "Back",
    btn_next: "Next",
    btn_another_church: "Another Church",
    placeholder_arabic_name: "Write your quadruple name in Arabic letters",
    placeholder_english_name: "Enter your quadruple name in English",
    placeholder_whatsapp: "+44 7123 456789",
    placeholder_otp: "123456",
    placeholder_education: "Search institution...",
    placeholder_address: "Enter your detailed address...",
    error_arabic_name_regex: "Please enter exactly 4 names separated by spaces, using only Arabic letters.",
    error_english_name_regex: "Please enter exactly 4 names separated by spaces, using only English letters.",
    error_dob_required: "Date of birth is required.",
    error_whatsapp_required: "WhatsApp number is required.",
    error_otp_missing: "Please verify your phone number by sending and entering the OTP.",
    error_otp_invalid: "Please enter a valid 6-digit OTP.",
    error_email_invalid: "Please enter a valid email address.",
    error_education_required: "Please enter your educational institution.",
    error_address_required: "Please enter your full address.",
    error_coords_missing: "Please capture your coordinates for visitation.",
    error_gov_required: "Please select a governorate.",
    error_church_missing: "Please select at least 1 church.",
    error_church_max: "You can select a maximum of 5 churches.",
    error_password_short: "Password must be at least 6 characters.",
    reg_confirm_password_label: "Confirm Password",
    error_confirm_password_required: "Please confirm your password.",
    placeholder_confirm_password: "Re-type password",
    step_9_title: "Profile Photo",
    step_10_title: "Set Password",
    reg_photo_label: "Profile Photo",
    reg_photo_placeholder: "Add photo",
    btn_rotate: "Rotate",
    btn_remove_photo: "Remove",
    btn_upload_photo: "Upload Photo",
    btn_take_photo: "Take Photo",
    btn_capture: "Capture",
    btn_cancel: "Cancel",
    btn_skip: "Skip",

    // Dashboard translations
    dashboard_header: "Dashboard",
    welcome: "Welcome Back,",
    blessing: '"Peace be to this house and to all that dwell in it." Have a blessed day.',
    next_liturgy: "Next Liturgy Booking",
    confession: "Confession Session",
    reserved: "Reserved Services",
    class_group: "Spiritual Class Group",
    wisdom_title: "Spiritual Wisdom",
    wisdom_quote: '"Do not be afraid of the combat, and do not run away from it. If you fall, get up again, pray to the Lord, and push forward. The Savior is always near to help you."',
    wisdom_author: "— St. Anthony the Great",
    katameros_title: "Katameros (Daily Reading)",
    psalm_heading: "Psalm 23:1-3",
    psalm_text: '"The Lord is my shepherd; I shall not want. He makes me to lie down in green pastures; He leads me beside the still waters..."',
    john_heading: "John 15:5",
    john_text: '"I am the vine, you are the branches. He who abides in Me, and I in him, bears much fruit; for without Me you can do nothing."',
    read_full: "Read Full Katameros",
    book_liturgy: "Book Divine Liturgy",
    notice_board: "Church Notice Board",
    sunday_liturgy: "Sunday Liturgy - June 14",
    wednesday_liturgy: "Wednesday Liturgy - June 17",
    feast_liturgy: "Feast of Ascension Liturgy - June 18",
    main_hall: "Main Hall (Coptic/English)",
    chapel: "St. Mary Chapel (Arabic/Coptic)",
    sanctuary: "Main Sanctuary (Feast Liturgy)",
    capacity_120: "Capacity: 120/150 booked",
    capacity_15: "Capacity: 15/40 booked",
    capacity_45: "Capacity: 45/200 booked",
    book_space: "Book Space",
    retreat_badge: "Retreat Announcement",
    retreat_title: "Youth Spiritual Retreat 2026",
    retreat_text: "Registration for our Summer Youth Retreat is officially open. The retreat will take place from July 24-26. Speak with Father Antonios to register.",
    bible_badge: "Bible Study",
    bible_title: "Summer Book study on Isaiah",
    bible_text: "Every Thursday evening at 7:30 PM in the Fellowship Hall. Bring your own Bible. Live stream will also be available on our channel.",
    view_notices: "View all notices",
    nav_dashboard: "Dashboard",
    nav_bookings: "Bookings",
    nav_katameros: "Katameros",
    nav_community: "Community",
    nav_settings: "Settings",
    profile_logged_in: "Logged in as:",
    profile_settings: "Profile Settings",
    profile_logout: "Log Out"
  },
  "ar-eg": {
    // Login translations
    title: "At Church",
    subtitle: "الأقباط الأرثوذكس",
    slogan: '"راسخون في الإيمان، متحدون في المحبة."',
    tab_login: "تسجيل الدخول",
    tab_register: "حساب جديد",
    email_label: "البريد الإلكتروني",
    password_label: "كلمة المرور",
    forgot_password: "نسيت؟",
    btn_signin: "تسجيل الدخول",
    demo_login_prefix: "حساب تجريبي:",
    register_name_label: "الاسم الكامل",
    confirm_password_label: "تأكيد كلمة المرور",
    btn_create_account: "إنشاء حساب",
    help: "مساعدة",
    privacy: "الخصوصية",
    terms: "الشروط",
    placeholder_email: "name@example.com",
    placeholder_password: "••••••••",
    placeholder_name: "مثال: فايز شنودة",
    placeholder_min_chars: "٦ أحرف على الأقل",
    placeholder_retype: "إعادة كتابة كلمة المرور",
    forgot_title: "إعادة تعيين كلمة المرور",
    forgot_instructions: "أدخل بريدك الإلكتروني المسجل لإعادة تعيين كلمة المرور.",
    forgot_instructions_step2: "تم إرسال رمز تحقق مؤقت إلى بريدك الإلكتروني.",
    mock_code_notice: "الرمز التجريبي: 123456",
    code_label: "رمز التحقق",
    new_password_label: "كلمة مرور جديدة",
    btn_reset_password: "إعادة تعيين كلمة المرور",
    btn_submit_new_password: "تحديث كلمة المرور",
    back_to_login: "العودة إلى تسجيل الدخول",
    placeholder_code: "أدخل ١٢٣٤٥٦",
    error_email_not_found: "البريد الإلكتروني غير موجود.",
    error_invalid_code: "رمز التحقق غير صالح. استخدم ١٢٣٤٥٦.",
    error_passwords_dont_match: "كلمتا المرور غير متطابقتين.",
    success_password_reset: "تمت إعادة تعيين كلمة المرور بنجاح! جاري تحويلك...",
    email_verified_msg: "تم التحقق من البريد الإلكتروني! أدخل رمز التحقق.",
    error_password_too_short: "يجب أن تكون كلمة المرور ٦ أحرف على الأقل.",
    step_1_title: "الخطوة ١ من ٣: البيانات الشخصية",
    step_2_title: "الخطوة ٢ من ٣: وسائل التواصل",
    step_3_title: "الخطوة ٣ من ٣: بيانات الكنيسة والحساب",
    reg_arabic_name_label: "الاسم رباعي بالعربية",
    reg_english_name_label: "الاسم بالكامل بالإنجليزية",
    reg_dob_label: "تاريخ الميلاد",
    reg_phone_label: "رقم الواتساب",
    btn_send_otp: "إرسال رمز التحقق",
    btn_send_email_link: "إرسال رابط التحقق",
    btn_sending_otp: "جاري الإرسال...",
    btn_sent_otp: "تم إرسال الرمز",
    email_link_sent_msg: "تم إرسال رابط التحقق! يرجى التحقق من بريدك الإلكتروني والنقر على الرابط لتأكيد حسابك.",
    reg_otp_label: "أدخل رمز مكون من ٦ أرقام",
    reg_otp_mock_notice: "الوضع التجريبي: أدخل أي ٦ أرقام.",
    reg_email_label: "البريد الإلكتروني (اختياري)",
    reg_education_label: "المدرسة / الكلية",
    reg_address_label: "العنوان بالتفصيل لزيارة الافتقاد",
    btn_get_coordinates: "تحديد الموقع الحالي (إحداثيات GPS)",
    reg_coords_captured: "تم التقاط الإحداثيات بنجاح.",
    reg_gov_label: "اختيار الكنيسة",
    reg_gov_placeholder: "اختر المحافظة...",
    gov_assiut: "أسيوط",
    gov_cairo: "القاهرة",
    gov_alexandria: "الإسكندرية",
    reg_church_placeholder: "اختر المحافظة أولاً.",
    reg_password_label: "إنشاء كلمة المرور",
    btn_back: "رجوع",
    btn_next: "التالي",
    btn_another_church: "كنيسة أخرى",
    placeholder_arabic_name: "اكتب اسمك رباعي باللغة العربية",
    placeholder_english_name: "اكتب اسمك رباعي باللغة الإنجليزية",
    placeholder_whatsapp: "+20 123 456 7890",
    placeholder_otp: "١٢٣٤٥٦",
    placeholder_education: "ابحث عن المؤسسة التعليمية...",
    placeholder_address: "أدخل عنوانك بالتفصيل...",
    error_arabic_name_regex: "الرجاء إدخال الاسم رباعي باللغة العربية تفصل بينها مسافات.",
    error_english_name_regex: "الرجاء إدخال الاسم بالكامل بالإنجليزية مكون من ٤ مقاطع تفصل بينها مسافات.",
    error_dob_required: "تاريخ الميلاد مطلوب.",
    error_whatsapp_required: "رقم الواتساب مطلوب.",
    error_otp_missing: "يرجى تأكيد رقم الهاتف عن طريق إرسال وإدخال رمز التحقق.",
    error_otp_invalid: "يرجى إدخال رمز تحقق صالح مكون من ٦ أرقام.",
    error_email_invalid: "يرجى إدخال بريد إلكتروني صحيح.",
    error_education_required: "يرجى إدخال المؤسسة التعليمية.",
    error_address_required: "يرجى إدخال العنوان بالكامل.",
    error_coords_missing: "يرجى التقاط إحداثيات موقعك الجغرافي لزيارة الافتقاد.",
    error_gov_required: "يرجى اختيار المحافظة.",
    error_church_missing: "يرجى اختيار كنيسة واحدة على الأقل.",
    error_church_max: "يمكنك اختيار ٥ كنائس كحد أقصى.",
    error_password_short: "يجب أن تتكون كلمة المرور من ٦ أحرف على الأقل.",
    reg_confirm_password_label: "تأكيد كلمة المرور",
    error_confirm_password_required: "يرجى تأكيد كلمة المرور.",
    placeholder_confirm_password: "أعد كتابة كلمة المرور",
    step_9_title: "الصورة الشخصية",
    step_10_title: "كلمة المرور",
    reg_photo_label: "الصورة الشخصية",
    reg_photo_placeholder: "إضافة صورة",
    btn_rotate: "تدوير",
    btn_remove_photo: "إزالة",
    btn_upload_photo: "رفع صورة",
    btn_take_photo: "التقاط صورة",
    btn_capture: "التقاط",
    btn_cancel: "إلغاء",
    btn_skip: "تخطي",

    // Dashboard translations
    dashboard_header: "لوحة التحكم",
    welcome: "أهلاً بك مجدداً،",
    blessing: '"سلامٌ لهذا البيت ولكل الساكنين فيه." نتمنى لك يوماً مباركاً.',
    next_liturgy: "الحجز القادم للقداس",
    confession: "جلسة الاعتراف",
    reserved: "الخدمات المحجوزة",
    class_group: "اجتماع الشباب الروحي",
    wisdom_title: "حكمة روحية",
    wisdom_quote: '"لا تخف من المحاربة ولا تهرب منها. إن سقطت قم ثانيةً، واصرخ إلى الرب، وامضِ للأمام. المخلص دائماً قريب ليعينك."',
    wisdom_author: "— القديس الأنبا أنطونيوس الكبير",
    katameros_title: "القطمارس (القراءة اليومية)",
    psalm_heading: "مزمور ٢٣: ١-٣",
    psalm_text: '"الرب راعيّ فلا يعوزني شيء. في مراعٍ خضر يربضني، إلى مياه الراحة يوردني..."',
    john_heading: "يوحنا ١٥: ٥",
    john_text: '"أنا الكرمة وأنتم الأغصان. الذي يثبت فيّ وأنا فيه هذا يأتي بثمر كثير، لأنكم بدوني لا تقدرون أن تفعلوا شيئاً."',
    read_full: "اقرأ القطمارس كاملاً",
    book_liturgy: "حجز قداس إلهي",
    notice_board: "لوحة إعلانات الكنيسة",
    sunday_liturgy: "قداس الأحد - ١٤ يونيو",
    wednesday_liturgy: "قداس الأربعاء - ١٧ يونيو",
    feast_liturgy: "قداس عيد الصعود - ١٨ يونيو",
    main_hall: "القاعة الرئيسية (قبطي/إنجليزي)",
    chapel: "كنيسة العذراء مريم (عربي/قبطي)",
    sanctuary: "الهيكل الرئيسي (قداس العيد)",
    capacity_120: "السعة: تم حجز ١٢٠/١٥٠",
    capacity_15: "السعة: تم حجز ١٥/٤٠",
    capacity_45: "السعة: تم حجز ٤٥/٢٠٠",
    book_space: "احجز مكانك",
    retreat_badge: "إعلان خلوة روحية",
    retreat_title: "الخلوة الروحية للشباب ٢٠٢٦",
    retreat_text: "باب التسجيل لخلوة الشباب الصيفية مفتوح رسمياً. ستقام الخلوة من ٢٤ إلى ٢٦ يوليو. يرجى التنسيق مع أبونا أنطونيوس للتسجيل.",
    bible_badge: "دراسة الكتاب المقدس",
    bible_title: "دراسة صيفية في سفر إشعياء",
    bible_text: "كل خميس مساءً الساعة ٧:٣٠ في قاعة المناسبات. يرجى إحضار كتابك المقدس. البث المباشر متاح أيضاً على قناتنا.",
    view_notices: "عرض كل الإعلانات",
    nav_dashboard: "الرئيسية",
    nav_bookings: "الحجوزات",
    nav_katameros: "القطمارس",
    nav_community: "المجتمع",
    nav_settings: "الإعدادات",
    profile_logged_in: "مسجل الدخول باسم:",
    profile_settings: "إعدادات الحساب",
    profile_logout: "تسجيل الخروج"
  },
  "fr": {
    // Login translations
    title: "At Church",
    subtitle: "Copte Orthodoxe",
    slogan: '" Ancrés dans la foi, unis dans l\'amour."',
    tab_login: "Se connecter",
    tab_register: "Nouveau compte",
    email_label: "Adresse e-mail",
    password_label: "Mot de passe",
    forgot_password: "Oublié ?",
    btn_signin: "Se connecter",
    demo_login_prefix: "Connexion démo :",
    register_name_label: "Nom complet",
    confirm_password_label: "Confirmer le mot de passe",
    btn_create_account: "Créer un compte",
    help: "Aide",
    privacy: "Confidentialité",
    terms: "Conditions",
    placeholder_email: "nom@exemple.com",
    placeholder_password: "••••••••",
    placeholder_name: "ex. Fayez Shenouda",
    placeholder_min_chars: "Min 6 caractères",
    placeholder_retype: "Saisir à nouveau",
    forgot_title: "Réinitialiser le mot de passe",
    forgot_instructions: "Entrez votre adresse e-mail enregistrée pour réinitialiser votre mot de passe.",
    forgot_instructions_step2: "Un code de vérification temporaire a été envoyé à votre e-mail.",
    mock_code_notice: "Code de démonstration: 123456",
    code_label: "Code de vérification",
    new_password_label: "Nouveau mot de passe",
    btn_reset_password: "Réinitialiser",
    btn_submit_new_password: "Mettre à jour le mot de passe",
    back_to_login: "Retour à la connexion",
    placeholder_code: "Saisir 123456",
    error_email_not_found: "Adresse e-mail non trouvée.",
    error_invalid_code: "Code de vérification invalide. Utilisez 123456.",
    error_passwords_dont_match: "Les mots de passe ne correspondent pas.",
    success_password_reset: "Réinitialisation réussie! Redirection...",
    email_verified_msg: "E-mail vérifié! Entrez le code de vérification.",
    error_password_too_short: "Le mot de passe doit comporter au moins 6 caractères.",
    step_1_title: "Étape 1 sur 3: Infos personnelles",
    step_2_title: "Étape 2 sur 3: Communication",
    step_3_title: "Étape 3 sur 3: Données de l'église & Compte",
    reg_arabic_name_label: "Nom quadruplé en arabe",
    reg_english_name_label: "Nom complet en anglais",
    reg_dob_label: "Date de naissance",
    reg_phone_label: "Numéro WhatsApp",
    btn_send_otp: "Envoyer le code de vérification",
    btn_send_email_link: "Envoyer le lien de vérification",
    btn_sending_otp: "Envoi...",
    btn_sent_otp: "Code envoyé",
    email_link_sent_msg: "Lien de vérification envoyé ! Veuillez consulter votre boîte de réception et cliquer sur le lien.",
    reg_otp_label: "Entrez le code à 6 chiffres",
    reg_otp_mock_notice: "Mode démo: Entrez 6 chiffres de votre choix.",
    reg_email_label: "Adresse e-mail (facultatif)",
    reg_education_label: "École / Université",
    reg_address_label: "Adresse pour les visites",
    btn_get_coordinates: "Obtenir les coordonnées GPS",
    reg_coords_captured: "Coordonnées capturées.",
    reg_gov_label: "Sélection de l'église",
    reg_gov_placeholder: "Sélectionnez le gouvernorat...",
    gov_assiut: "Assiout",
    gov_cairo: "Le Caire",
    gov_alexandria: "Alexandrie",
    reg_church_placeholder: "Sélectionnez d'abord un gouvernorat.",
    reg_password_label: "Créer un mot de passe",
    btn_back: "Retour",
    btn_next: "Suivant",
    btn_another_church: "Autre Église",
    placeholder_arabic_name: "Entrez votre nom quadruplé en arabe",
    placeholder_english_name: "Entrez votre nom quadruplé en anglais",
    placeholder_whatsapp: "+20 123 456 7890",
    placeholder_otp: "123456",
    placeholder_education: "Rechercher l'établissement...",
    placeholder_address: "Entrez votre adresse détaillée...",
    error_arabic_name_regex: "Veuillez saisir exactement 4 noms séparés par des espaces, en utilisant uniquement des lettres arabes.",
    error_english_name_regex: "Veuillez saisir exactement 4 noms séparés par des espaces, en utilisant uniquement des lettres anglaises.",
    error_dob_required: "La date de naissance est obligatoire.",
    error_whatsapp_required: "Le numéro WhatsApp est obligatoire.",
    error_otp_missing: "Veuillez vérifier votre numéro de téléphone en saisissant le code OTP.",
    error_otp_invalid: "Veuillez saisir un code OTP valide à 6 chiffres.",
    error_email_invalid: "Veuillez saisir une adresse e-mail valide.",
    error_education_required: "Veuillez saisir votre établissement d'enseignement.",
    error_address_required: "Veuillez saisir votre adresse complète.",
    error_coords_missing: "Veuillez capturer vos coordonnées pour la visite.",
    error_gov_required: "Veuillez sélectionner un gouvernorat.",
    error_church_missing: "Veuillez sélectionner au moins 1 église.",
    error_church_max: "Vous pouvez sélectionner un maximum de 5 églises.",
    error_password_short: "Le mot de passe doit comporter au moins 6 caractères.",
    reg_confirm_password_label: "Confirmer le mot de passe",
    error_confirm_password_required: "Veuillez confirmer votre mot de passe.",
    placeholder_confirm_password: "Retapez le mot de passe",
    step_9_title: "Photo de Profil",
    step_10_title: "Mot de Passe",
    reg_photo_label: "Photo de Profil",
    reg_photo_placeholder: "Ajouter",
    btn_rotate: "Pivoter",
    btn_remove_photo: "Supprimer",
    btn_upload_photo: "Télécharger",
    btn_take_photo: "Prendre Photo",
    btn_capture: "Capturer",
    btn_cancel: "Annuler",
    btn_skip: "Passer",

    // Dashboard translations
    dashboard_header: "Tableau de Bord",
    welcome: "Bienvenue,",
    blessing: '"Paix à cette maison et à tous ceux qui l\'habitent." Passez une journée bénie.',
    next_liturgy: "Prochaine Liturgie Réservez",
    confession: "Session de Confession",
    reserved: "Services Réservés",
    class_group: "Groupe de Jeunesse",
    wisdom_title: "Sagesse Spirituelle",
    wisdom_quote: '"Ne craignez pas le combat et ne le fuyez pas. Si vous tombez, relevez-vous, priez le Seigneur et avancez. Le Sauveur est toujours proche pour vous aider."',
    wisdom_author: "— St. Antoine le Grand",
    katameros_title: "Katameros (Lecture Quotidienne)",
    psalm_heading: "Psaume 23:1-3",
    psalm_text: '"Le Seigneur est mon berger ; je ne manquerai de rien. Il me fait reposer dans de verts pâturages ; Il me dirige près des eaux paisibles..."',
    john_heading: "Jean 15:5",
    john_text: '"Je suis le cep, vous êtes les sarments. Celui qui demeure en Moi et en qui Je demeure porte beaucoup de fruit, car sans Moi vous ne pouvez rien faire."',
    read_full: "Lire tout le Katameros",
    book_liturgy: "Réserver une Divine Liturgie",
    notice_board: "Tableau d'Affichage de l'Église",
    sunday_liturgy: "Liturgie du Dimanche - 14 Juin",
    wednesday_liturgy: "Liturgie du Mercredi - 17 Juin",
    feast_liturgy: "Liturgie de l'Ascension - 18 Juin",
    main_hall: "Grande Salle (Copte/Anglais)",
    chapel: "Chapelle Ste. Marie (Arabe/Copte)",
    sanctuary: "Sanctuaire Principal (Liturgie de Fête)",
    capacity_120: "Capacité : 120/150 réservés",
    capacity_15: "Capacité : 15/40 réservés",
    capacity_45: "Capacité : 45/200 réservés",
    book_space: "Réserver",
    retreat_badge: "Annonce de Retraite",
    retreat_title: "Retraite Spirituelle des Jeunes 2026",
    retreat_text: "L'inscription pour notre Retraite d'Été des Jeunes est ouverte. Elle aura lieu du 24 au 26 juillet. Parlez au Père Antonios pour vous inscrire.",
    bible_badge: "Étude Biblique",
    bible_title: "Étude estivale sur le livre d'Isaïe",
    bible_text: "Chaque jeudi soir à 19h30 dans la salle paroissiale. Apportez votre Bible. Diffusion en direct disponible.",
    view_notices: "Voir toutes les annonces",
    nav_dashboard: "Tableau de Bord",
    nav_bookings: "Réservations",
    nav_katameros: "Katameros",
    nav_community: "Communauté",
    nav_settings: "Paramètres",
    profile_logged_in: "Connecté en tant que :",
    profile_settings: "Paramètres du Profil",
    profile_logout: "Se Déconnecter"
  },
  "de": {
    // Login translations
    title: "At Church",
    subtitle: "Koptisch-Orthodox",
    slogan: '" Verwurzelt im Glauben, vereint in der Liebe."',
    tab_login: "Anmelden",
    tab_register: "Neues Konto",
    email_label: "E-Mail-Adresse",
    password_label: "Passwort",
    forgot_password: "Vergessen?",
    btn_signin: "Anmelden",
    demo_login_prefix: "Demo-Anmeldung:",
    register_name_label: "Vollständiger Name",
    confirm_password_label: "Passwort bestätigen",
    btn_create_account: "Konto erstellen",
    help: "Hilfe",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    placeholder_email: "name@beispiel.de",
    placeholder_password: "••••••••",
    placeholder_name: "z. B. Fayez Shenouda",
    placeholder_min_chars: "Mindestens 6 Zeichen",
    placeholder_retype: "Passwort wiederholen",
    forgot_title: "Passwort zurücksetzen",
    forgot_instructions: "Geben Sie Ihre registrierte E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen.",
    forgot_instructions_step2: "Ein temporärer Bestätigungscode wurde an Ihre E-Mail-Adresse gesendet.",
    mock_code_notice: "Demo-Code: 123456",
    code_label: "Bestätigungscode",
    new_password_label: "Neues Passwort",
    btn_reset_password: "Passwort zurücksetzen",
    btn_submit_new_password: "Passwort aktualisieren",
    back_to_login: "Zurück zur Anmeldung",
    placeholder_code: "Geben Sie 123456 ein",
    error_email_not_found: "E-Mail-Adresse nicht gefunden.",
    error_invalid_code: "Ungültiger Bestätigungscode. Verwenden Sie 123456.",
    error_passwords_dont_match: "Passwörter stimmen nicht überein.",
    success_password_reset: "Passwort erfolgreich zurückgesetzt! Weiterleitung...",
    email_verified_msg: "E-Mail verifiziert! Geben Sie den Bestätigungscode ein.",
    error_password_too_short: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    step_1_title: "Schritt 1 von 3: Persönliche Daten",
    step_2_title: "Schritt 2 von 3: Kommunikation",
    step_3_title: "Schritt 3 von 3: Kirchendaten & Konto",
    reg_arabic_name_label: "Vierteiliger Name auf Arabisch",
    reg_english_name_label: "Vollständiger Name auf Englisch",
    reg_dob_label: "Geburtsdatum",
    reg_phone_label: "WhatsApp-Nummer",
    btn_send_otp: "Bestätigungscode senden",
    btn_send_email_link: "Bestätigungslink senden",
    btn_sending_otp: "Senden...",
    btn_sent_otp: "Code gesendet",
    email_link_sent_msg: "Bestätigungslink gesendet! Bitte überprüfen Sie Ihren Posteingang und klicken Sie auf den Link.",
    reg_otp_label: "6-stelligen Code eingeben",
    reg_otp_mock_notice: "Demo-Modus: Beliebige 6 Ziffern eingeben.",
    reg_email_label: "E-Mail-Adresse (Optional)",
    reg_education_label: "Schule / Hochschule",
    reg_address_label: "Adresse für Besuche",
    btn_get_coordinates: "Aktuelle GPS-Koordinaten abrufen",
    reg_coords_captured: "Koordinaten erfasst.",
    reg_gov_label: "Kirchenauswahl",
    reg_gov_placeholder: "Gouvernement auswählen...",
    gov_assiut: "Asyut",
    gov_cairo: "Kairo",
    gov_alexandria: "Alexandria",
    reg_church_placeholder: "Wählen Sie zuerst ein Gouvernement aus.",
    reg_password_label: "Passwort erstellen",
    btn_back: "Zurück",
    btn_next: "Weiter",
    btn_another_church: "Andere Kirche",
    placeholder_arabic_name: "Geben Sie Ihren vierteiligen Namen auf Arabisch ein",
    placeholder_english_name: "Geben Sie Ihren vierteiligen Namen auf Englisch ein",
    placeholder_whatsapp: "+20 123 456 7890",
    placeholder_otp: "123456",
    placeholder_education: "Institution suchen...",
    placeholder_address: "Geben Sie Ihre detaillierte Adresse ein...",
    error_arabic_name_regex: "Bitte geben Sie genau 4 durch Leerzeichen getrennte Namen ein, die nur arabische Buchstaben enthalten.",
    error_english_name_regex: "Bitte geben Sie genau 4 durch Leerzeichen getrennte Namen ein, die nur englische Buchstaben enthalten.",
    error_dob_required: "Geburtsdatum ist erforderlich.",
    error_whatsapp_required: "WhatsApp-Nummer ist erforderlich.",
    error_otp_missing: "Bitte verifizieren Sie Ihre Telefonnummer, indem Sie das OTP senden und eingeben.",
    error_otp_invalid: "Bitte geben Sie eine gültige 6-stellige OTP ein.",
    error_email_invalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    error_education_required: "Bitte geben Sie Ihre Bildungseinrichtung ein.",
    error_address_required: "Bitte geben Sie Ihre vollständige Adresse ein.",
    error_coords_missing: "Bitte erfassen Sie Ihre Koordinaten für den Besuch.",
    error_gov_required: "Bitte wählen Sie ein Gouvernement aus.",
    error_church_missing: "Bitte wählen Sie mindestens 1 Kirche aus.",
    error_church_max: "Sie können maximal 5 Kirchen auswählen.",
    error_password_short: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    reg_confirm_password_label: "Passwort bestätigen",
    error_confirm_password_required: "Bitte bestätigen Sie Ihr Passwort.",
    placeholder_confirm_password: "Passwort wiederholen",
    step_9_title: "Profilbild",
    step_10_title: "Passwort",
    reg_photo_label: "Profilbild",
    reg_photo_placeholder: "Bild",
    btn_rotate: "Drehen",
    btn_remove_photo: "Löschen",
    btn_upload_photo: "Hochladen",
    btn_take_photo: "Kamera",
    btn_capture: "Aufnehmen",
    btn_cancel: "Abbrechen",
    btn_skip: "Überspringen",

    // Dashboard translations
    dashboard_header: "Dashboard",
    welcome: "Willkommen zurück,",
    blessing: '"Friede sei diesem Hause und allen, die darin wohnen." Haben Sie einen gesegneten Tag.',
    next_liturgy: "Nächste Liturgiebuchung",
    confession: "Beichtsitzung",
    reserved: "Reservierte Dienste",
    class_group: "Spiritual Youth Group",
    wisdom_title: "Geistliche Weisheit",
    wisdom_quote: '"Fürchte dich nicht vor dem Kampf und laufe nicht davon. Wenn du fällst, stehe wieder auf, bete zum Herrn und dränge vorwärts. Der Retter ist immer nah, um dir zu helfen."',
    wisdom_author: "— Hl. Antonius der Große",
    katameros_title: "Katameros (Tägliche Lesung)",
    psalm_heading: "Psalm 23:1-3",
    psalm_text: '"Der Herr ist mein Hirte; mir wird nichts mangeln. Er weidet mich auf einer grünen Aue und führet mich zum frischen Wasser..."',
    john_heading: "Johannes 15:5",
    john_text: '"Ich bin der Weinstock, ihr seid die Reben. Wer in Mir bleibt und Ich in ihm, der bringt viel Frucht; denn ohne Ich könnt ihr nichts tun."',
    read_full: "Vollständiges Katameros lesen",
    book_liturgy: "Göttliche Liturgie buchen",
    notice_board: "Kirchen-Mitteilungsblatt",
    sunday_liturgy: "Sonntagsliturgie - 14. Juni",
    wednesday_liturgy: "Mittwochsliturgie - 17. Juni",
    feast_liturgy: "Auffahrtsliturgie - 18. Juni",
    main_hall: "Hauptsaal (Koptisch/Englisch)",
    chapel: "St. Marien Kapelle (Arabisch/Koptisch)",
    sanctuary: "Hauptheiligtum (Festliturgie)",
    capacity_120: "Kapazität: 120/150 gebucht",
    capacity_15: "Kapazität: 15/40 gebucht",
    capacity_45: "Kapazität: 45/200 gebucht",
    book_space: "Buchen",
    retreat_badge: "Retreat-Ankündigung",
    retreat_title: "Jugend-Spiritual-Retreat 2026",
    retreat_text: "Die Registrierung für das Sommer-Jugend-Retreat ist offen. Es findet vom 24.-26. Juli statt. Sprechen Sie mit Vater Antonios zur Buchung.",
    bible_badge: "Bibelstudium",
    bible_title: "Sommerbuchstudium über Jesaja",
    bible_text: "Jeden Donnerstagabend um 19:30 Uhr im Gemeindesaal. Bitte eigene Bibel mitbringen. Live-Stream ist verfügbar.",
    view_notices: "Alle Anzeigen sehen",
    nav_dashboard: "Dashboard",
    nav_bookings: "Buchungen",
    nav_katameros: "Katameros",
    nav_community: "Gemeinschaft",
    nav_settings: "Einstellungen",
    profile_logged_in: "Angemeldet als:",
    profile_settings: "Profil-Einstellungen",
    profile_logout: "Abmelden"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en-us");

  useEffect(() => {
    const saved = localStorage.getItem("preferredLanguage") as Language;
    if (saved && translationsData[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    if (translationsData[lang]) {
      localStorage.setItem("preferredLanguage", lang);
      setLanguageState(lang);
    }
  };

  const t = (key: string): string => {
    return translationsData[language]?.[key] || translationsData["en-us"]?.[key] || key;
  };

  const dir = language === "ar-eg" ? "rtl" : "ltr";

  // Dynamic direction and lang attribute on document tag
  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", language);
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
